### ISSUE TITLE
Can't run data/add_answer.py

### ISSUE THREAD

**Issue by Tianchen627** [guotong1988/Rule-SQL#1]
ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
```
0
Error closing cursor
Traceback (most recent call last):
  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1266, in fetchone
    row = self._fetchone_impl()
  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1146, in _fetchone_impl
    return self.cursor.fetchone()
sqlite3.ProgrammingError: Cannot operate on a closed database.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\base.py", line 1335, in _safe_close_cursor
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Traceback (most recent call last):

  File "<ipython-input-16-f49e023f87e6>", line 1, in <module>
    runfile('F:/Rule-SQL-master/data/add_answer.py', wdir='F:/Rule-SQL-master/data')

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/Rule-SQL-master/data/add_answer.py", line 38, in <module>
    process(train_data,"train_with_answer.jsonl",engine_train)

  File "F:/Rule-SQL-master/data/add_answer.py", line 25, in process
    answer = engine_.execute_query_v2(item["table_id"],item["sql"])

  File "F:\Rule-SQL-master\sqlnet\dbengine.py", line 27, in execute_query_v2
    return self.execute(table_id, query["sel"], query["agg"], query["conds"], *args, **kwargs)

  File "F:\Rule-SQL-master\sqlnet\dbengine.py", line 32, in execute
    table_info = self.db.query('SELECT sql from sqlite_master WHERE tbl_name = :name', name=table_id).all()[0].sql.replace('\n','')

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 195, in all
    rows = list(self)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 126, in __iter__
    yield next(self)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 136, in __next__
    nextrow = next(self._rows)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 365, in <genexpr>
    row_gen = (Record(cursor.keys(), row) for row in cursor)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 944, in __iter__
    row = self.fetchone()

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1274, in fetchone
    e, None, None, self.cursor, self.context

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1266, in fetchone
    row = self._fetchone_impl()

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1146, in _fetchone_impl
    return self.cursor.fetchone()

ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/f405)




runfile('F:/Rule-SQL-master/data/add_answer.py', wdir='F:/Rule-SQL-master/data')
Reloaded modules: sqlnet.dbengine, rl.train_rl, bert.tokenization, bert.modeling, sqlova, sqlova.utils, sqlova.utils.utils_wikisql, sqlova.utils.utils, sqlova.utils.wikisql_formatter, sqlova.model, sqlova.model.nl2sql, sqlova.model.nl2sql.wikisql_models, train
0
Error closing cursor
Traceback (most recent call last):
  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1266, in fetchone
    row = self._fetchone_impl()
  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1146, in _fetchone_impl
    return self.cursor.fetchone()
sqlite3.ProgrammingError: Cannot operate on a closed database.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\base.py", line 1335, in _safe_close_cursor
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Traceback (most recent call last):

  File "<ipython-input-17-f49e023f87e6>", line 1, in <module>
    runfile('F:/Rule-SQL-master/data/add_answer.py', wdir='F:/Rule-SQL-master/data')

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/Rule-SQL-master/data/add_answer.py", line 38, in <module>
    process(train_data,"train_with_answer.jsonl",engine_train)

  File "F:/Rule-SQL-master/data/add_answer.py", line 25, in process
    answer = engine_.execute_query_v2(item["table_id"],item["sql"])

  File "F:\Rule-SQL-master\sqlnet\dbengine.py", line 27, in execute_query_v2
    return self.execute(table_id, query["sel"], query["agg"], query["conds"], *args, **kwargs)

  File "F:\Rule-SQL-master\sqlnet\dbengine.py", line 32, in execute
    table_info = self.db.query('SELECT sql from sqlite_master WHERE tbl_name = :name', name=table_id).all()[0].sql.replace('\n','')

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 195, in all
    rows = list(self)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 126, in __iter__
    yield next(self)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 136, in __next__
    nextrow = next(self._rows)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\records.py", line 365, in <genexpr>
    row_gen = (Record(cursor.keys(), row) for row in cursor)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 944, in __iter__
    row = self.fetchone()

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1274, in fetchone
    e, None, None, self.cursor, self.context

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1266, in fetchone
    row = self._fetchone_impl()

  File "E:\anaconda\envs\tensorflow-gpu\lib\site-packages\sqlalchemy\engine\result.py", line 1146, in _fetchone_impl
    return self.cursor.fetchone()

ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/f405)
```
Could u tell me how can I fix it.
Thanks a lot!
感谢

**Comment by Tianchen627** [comment]
I have found ur solution on https://blog.csdn.net/guotong1988/article/details/102892709.
hhh
